// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjlRpiFcxsJRNqdI_Kr-Drz5cz0SI1Qz0',
    appId: '1:996889960936:web:003a72961bab241cf9c45d',
    messagingSenderId: '996889960936',
    projectId: 'agroapp-e54d0',
    authDomain: 'agroapp-e54d0.firebaseapp.com',
    storageBucket: 'agroapp-e54d0.appspot.com',
    measurementId: 'G-B5S4DKXZP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwDOoEFpr3RsG1X1dxbB3fKu0kCwpDApI',
    appId: '1:996889960936:android:af9e0c57a70547fef9c45d',
    messagingSenderId: '996889960936',
    projectId: 'agroapp-e54d0',
    storageBucket: 'agroapp-e54d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX14Ql1b2wjR2IxyTLHY9cCHxxjQoeGOo',
    appId: '1:996889960936:ios:ac6959168f042743f9c45d',
    messagingSenderId: '996889960936',
    projectId: 'agroapp-e54d0',
    storageBucket: 'agroapp-e54d0.appspot.com',
    iosClientId: '996889960936-4pejpdgliajbjb9iegae4skl1l3k13q0.apps.googleusercontent.com',
    iosBundleId: 'com.example.trabalho1',
  );
}
